// Mocks generated by Mockito 5.4.6 from annotations
// in timo/test/features/session/cubit/session_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:timo/features/session/models/focus_session_model.dart' as _i6;
import 'package:timo/features/session/repo/session_repo.dart' as _i3;
import 'package:timo/utils/error.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SessionRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockSessionRepo extends _i1.Mock implements _i3.SessionRepo {
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.FocusSessionModel>>
  createDailySession() =>
      (super.noSuchMethod(
            Invocation.method(#createDailySession, []),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i6.FocusSessionModel>
                >.value(
                  _FakeEither_0<_i5.Failure, _i6.FocusSessionModel>(
                    this,
                    Invocation.method(#createDailySession, []),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i6.FocusSessionModel>
                >.value(
                  _FakeEither_0<_i5.Failure, _i6.FocusSessionModel>(
                    this,
                    Invocation.method(#createDailySession, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.FocusSessionModel>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.FocusSessionModel?>>
  getActiveOrTodaySession() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveOrTodaySession, []),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i6.FocusSessionModel?>
                >.value(
                  _FakeEither_0<_i5.Failure, _i6.FocusSessionModel?>(
                    this,
                    Invocation.method(#getActiveOrTodaySession, []),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i6.FocusSessionModel?>
                >.value(
                  _FakeEither_0<_i5.Failure, _i6.FocusSessionModel?>(
                    this,
                    Invocation.method(#getActiveOrTodaySession, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.FocusSessionModel?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> syncSession(
    String? sessionId,
    int? durationSeconds,
    String? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#syncSession, [
              sessionId,
              durationSeconds,
              status,
            ]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#syncSession, [
                  sessionId,
                  durationSeconds,
                  status,
                ]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, void>>.value(
                  _FakeEither_0<_i5.Failure, void>(
                    this,
                    Invocation.method(#syncSession, [
                      sessionId,
                      durationSeconds,
                      status,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> completeSession(
    String? sessionId,
    int? durationSeconds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#completeSession, [sessionId, durationSeconds]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#completeSession, [
                  sessionId,
                  durationSeconds,
                ]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, void>>.value(
                  _FakeEither_0<_i5.Failure, void>(
                    this,
                    Invocation.method(#completeSession, [
                      sessionId,
                      durationSeconds,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);
}
